# Site settings
title: st4rdog.github.io
email: your-email@domain.com
description: > # this means ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://localhost:4000"
#url: "http://st4rdog.github.io"

markdown: kramdown

collections:
  news:
    output: true
    permalink: /news/:path/
  authors:
    output: true
    permalink: /author/:path/
  tutorials:
    output: false
    permalink: /tutorial/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single-post
  - scope:
      path: ""
      type: news
    values:
      layout: single-generic
  - scope:
      path: ""
      type: authors
    values:
      layout: single-author
  - scope:
      path: ""
      type: tutorials
    values:
      layout: single-generic