# NOTES
# Link to article example: <a href="{{ site.url }}{{ site.url-references-unity }}gameobject"></a>
# Link image example:      <img src="{{ site.baseurl }}{{ site.url-imgs }}{{ page.url }}001.png" />
# Link external:           <a href="http://" class="external"></a>

# SITE SETTINGS
title       : Unity Tutorials!
email       : st4rdog@gmail.com
description : > # this means ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# URLS - SITE
baseurl : "" # the subpath of your site, e.g. /blog/
#url     : "http://localhost:4000"
url     : "https://st4rdog.github.io"

# URLS - CONTENT
url-imgs      : "/imgs"
url-imgs-site : "/imgs/site"
url-media     : "/media"

url-tutorials-game         : "/tutorial/unity/game/"
url-tutorials-system       : "/tutorial/unity/system/"
url-tutorials-graphics     : "/tutorial/unity/graphics/"

url-references-programming : "/reference/programming/"
url-references-unity       : "/reference/unity/"
url-references-graphics    : "/reference/graphics/"

# URLS - EXTERNAL
unity-url          : "http://unity3d.com"
unity-download-url : "http://forum.unity3d.com"

# GLOBALS
patreon-title : "Temporarily exclusive to Patrons only!"

# SETTINGS - GENERAL
markdown: kramdown
sass:
    sass_dir: _sass

indexShowDisabled : true

# COLLECTIONS
collections:
  news:
    output    : true
    permalink : /news/:path/
  authors:
    output    : true
    permalink : /author/:path/
  tutorials:
    output    : true
    permalink : /tutorial/:path/
  references:
    output    : true
    permalink : /reference/:path/

# PAGE LAYOUTS
defaults:
  - scope:
      path: ""
      type: authors
    values:
      layout: single-author
  - scope:
      path: ""
      type: tutorials
    values:
      layout: single-generic
  - scope:
      path: ""
      type: references
    values:
      layout: single-generic
